export const DATA = [
    {
        id: "1",
        title: "The Flying Sausage",
        body: "AS U BEING MY FRIEND I WILL WARN ABOUT MY HUMAN BEING IN THE TELESCOPE. BUT WHAT I REALLY NEED TO TALK TO U ABOUT IS THE FLYING SAUSAGE INCIDENT I DON’T THINK I TALKED TO U ABOUT THIS BUT U REALLY SHOULD KNOW THAT I AM SECRETLY A FLYING SAUSAGE NOT ONLY AM I A FLYING...",
    },
    {
        id: "2",
        title: "The Young Hotwing",
        body: "DID U KNOW THAT A LONG TIME AGO THERE ONCE WAS A YOUNG HOT WING HE WAS A VERY NICE HOT WING EXCEPT HE WANTED TO HE TOMATO'S NOT JUST NORMAL TAMATO'S BUT TOMATO'S FROM A CLOWNS NOSE. HE HAD TO HAVE THE CLOWNS NOSE'S FOR EVERY MEAL BUT THEY HAD TO BE USED. THIS HOT WING...",
    },
    {
        id: "3",
        title: "THE RANDOM JELLYFISH",
        body: "THE CLEANED DERIVATIVE BETTERS THE DIVERSE SOUNDTRACK. A CLEAN MESSAGE RECYCLES UGLY FISH. UGLY FISH WATCHES MEAN BETTY THROUGHOUT THE REALISTIC JUSTICE. UGLY FISH ABSTRACTS MEAN BETTY. A COOK GEARS MEAN BETTY. UNDER A LAWN HUNTS A TALENT. HIS BAY BONUS TWISTS. FLABBY...",
    },
    {
        id: "4",
        title: "RIBBONS BUTT",
        body: "THE RUBBISH SLIDES. RIBBON'S BUTT SOAPS PALATO ON TOP OF THE INHERITANCE. RIBBON'S BUTT CERTIFIES PALATO. PALATO JUMPS UNDERNEATH HER DESTROYED STEEL. EACH AWARE ANCESTOR BARKS OUTSIDE EVERY STRETCHING EYESIGHT. A CONSUMING BLACKBOARD PADS RIBBON'S BUTT UNDERNEATH A...",
    },
    ];